### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by cookta2012** [RoqueDeicide/CryCIL#8]
CryEngine 5.0 already has a C# binding

**Comment by RoqueDeicide** [comment]
I know, it's quite different from CryCIL, both have their advantages: CryEngine's is less limited and is cross-compatible, while CryCIL is coded for better performance, has vastly more expansive Mono interface for C++ code and has far better documentation.

**Comment by cookta2012** [comment]
Ok I will give it a try, what version of CryEngine is necessary? for CryCIL?

**Comment by RoqueDeicide** [comment]
Don't try it yet, I'm in progress of updating it to work with CryEngine 5, then I will update code to 5.1, and then I'll proceed to do start-up debugging and lastly I will debug parts that will allow me to re-create the code of CryEngine C# framework samples (like Sydewinder). Until then CryCIL is practically unusable.

I cannot give any definite ETAs, since my productivity is hindered by a health problem that I'm currently resolving (might take up to a half of the year).

**Comment by cookta2012** [comment]
Most definitely take care of yourself last thing we need is another person
out of commission permanently. No rush.
